import Head from 'next/head'
import Image from 'next/image'
import CallToAction from '../components/CallToAction'
import Storyblok, {useStoryblok} from '../lib/storyblok'

import styles from '../styles/Home.module.css'

function Home({ ctas }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {ctas.map((cta, i) => (
            <CallToAction key={i} {...cta} />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  let preview = process.env.PREVIEW === 'true'
  // home is the default slug for the homepage in Storyblok
  let slug = 'new-page'
  // load the published content outside of the preview mode
  let sbParams = {
    version: 'published', // or 'published'
    resolve_links: '1'
  }

  if (preview) {
    // load the draft version inside of the preview mode
    sbParams.version = 'draft'
    sbParams.cv = Date.now()
    
  }

  let {data} = await Storyblok.get(`cdn/stories/${slug}`, sbParams)

  //console.log(data?.story?.content?.body[0].columns)


  // By returning { props: { ctas } }, the CallToAction components
  // will receive `ctas` as a prop at build time
  // Strong Assumption: in the story as first element
  // data?.story?.content?.body[0]
  // there is a grid. In the grid (columns) there are
  // Call To Action Components
  return {
    props: {
      ctas: data?.story?.content?.body[0].columns ? data?.story?.content?.body[0].columns : [],
      preview,

    },
    revalidate: 3600, // revalidate every hour
  }
}
export default Home